repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
        args:
          - --unsafe
      - id: check-symlinks
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.77.1
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
        exclude: '^modules|^example|^tools'
      - id: terraform_validate
        exclude: '^examples|^modules'

      - id: terraform_tflint
        exclude: '^examples'
        args:
          - --args=--config=__GIT_WORKING_DIR__/.config/tflint.hcl
          - --env-vars=TFLINT_LOG="info"
