#trigger:
#  batch: true
#  branches:
#    include:
#      - master
#  paths:
#    include:
#      - '*'
#
#pr:
#  branches:
#    include:
#      - '*'

trigger: none
pr: none

variables:
  - name: TF_LOG
    value: INFO
  - name: WORKING_DIR
    value: '$(System.DefaultWorkingDirectory)'

stages:
  - stage: "Terraform_CI"
    displayName: "Terraform Validate"
    jobs:
      - job: Terraform_CI
        displayName: "Terraform Validate"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
            fetchDepth: 0

          - task: TerraformInstaller@0
            displayName: 'Terraform Installer'
            inputs:
              terraformVersion: 'latest'

          - script: terraform -v
            displayName: 'Terraform Version'
            workingDirectory: '$(WORKING_DIR)'

          - script: terraform init -backend=false
            displayName: 'Terraform Init'
            workingDirectory: '$(WORKING_DIR)'

          - script: terraform validate
            displayName: 'Terraform Validate'
            workingDirectory: '$(WORKING_DIR)'

          - script: terraform fmt -check
            displayName: 'Terraform Format'
            workingDirectory: '$(WORKING_DIR)'
